databases:
  - name: graphene_test_db
    databaseName: graphene_test_db
    user: graphene_test_db_user

services:
  - type: web
    name: graphene-django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: graphene_test_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4